blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/voseghale/gorilla-tsdb#readme
    about: Check the documentation before opening an issue
  - name: Discussions
    url: https://github.com/voseghale/gorilla-tsdb/discussions
    about: Ask questions and discuss ideas
